<a href="https://colab.research.google.com/github/vlad-pirvu/PyTorch_Learning/blob/main/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch
import torch

# Create random tensor
tensor = torch.rand(7,7)
tensor

tensor([[0.6596, 0.9373, 0.4758, 0.8205, 0.6132, 0.8703, 0.1989],
        [0.9261, 0.8206, 0.1212, 0.3185, 0.0920, 0.1475, 0.2862],
        [0.8077, 0.9422, 0.9933, 0.9271, 0.8895, 0.6502, 0.6652],
        [0.4305, 0.9130, 0.6301, 0.9184, 0.8179, 0.8250, 0.0495],
        [0.3438, 0.6796, 0.9095, 0.9578, 0.5216, 0.1681, 0.5946],
        [0.4345, 0.8346, 0.2639, 0.4235, 0.3102, 0.1710, 0.7069],
        [0.5913, 0.1844, 0.5564, 0.1392, 0.7752, 0.8260, 0.0853]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
tensor2 = torch.rand(1,7)
tensor2

# Perform matrix multiplication
#tensor3 = torch.matmul(tensor,tensor2)
tensor3 = torch.matmul(tensor, tensor2.T)
print(tensor)
print(tensor2)
print(tensor2.T)
print(tensor3)

tensor([[0.6596, 0.9373, 0.4758, 0.8205, 0.6132, 0.8703, 0.1989],
        [0.9261, 0.8206, 0.1212, 0.3185, 0.0920, 0.1475, 0.2862],
        [0.8077, 0.9422, 0.9933, 0.9271, 0.8895, 0.6502, 0.6652],
        [0.4305, 0.9130, 0.6301, 0.9184, 0.8179, 0.8250, 0.0495],
        [0.3438, 0.6796, 0.9095, 0.9578, 0.5216, 0.1681, 0.5946],
        [0.4345, 0.8346, 0.2639, 0.4235, 0.3102, 0.1710, 0.7069],
        [0.5913, 0.1844, 0.5564, 0.1392, 0.7752, 0.8260, 0.0853]])
tensor([[0.7994, 0.1139, 0.9496, 0.3027, 0.3847, 0.0210, 0.8482]])
tensor([[0.7994],
        [0.1139],
        [0.9496],
        [0.3027],
        [0.3847],
        [0.0210],
        [0.8482]])
tensor([[1.7571],
        [1.3264],
        [2.8969],
        [1.6984],
        [2.2143],
        [1.5437],
        [1.4521]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor = torch.rand(7,7)
tensor2 = torch.rand(1,7)

# Matrix multiply tensors
tensor3 = torch.matmul(tensor, tensor2.T)
print(tensor)
print(tensor2)
print(tensor2.T)
print(tensor3)
tensor3.shape

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]])
tensor([[0.4820],
        [0.8198],
        [0.9971],
        [0.6984],
        [0.5675],
        [0.8352],
        [0.2056]])
tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


torch.Size([7, 1])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
import torch

# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
torch.cuda.is_available()

# Create two random tensors on GPU
tensor1 = torch.rand(2,3)
tensor2 = torch.rand(2,3)

tensor1gpu = tensor1.to('cuda')
tensor2gpu = tensor2.to('cuda')

print(tensor1gpu)
print(tensor2gpu)





tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B
#print(tensor1gpu.shape, tensor2gpu.shape)
tensor3gpu = torch.matmul(tensor1gpu,tensor2gpu.T)
print(tensor3gpu, tensor3gpu.shape)

torch.Size([2, 3]) torch.Size([2, 3])
tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0') torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
print(torch.max(tensor3gpu))
# Find min
print(torch.min(tensor3gpu))


tensor(0.5617, device='cuda:0')
tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
print(tensor3gpu.argmax())

# Find arg min
print(tensor3gpu.argmin())

tensor(3, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
import torch
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor1 = torch.rand(1,1,1,10)

# Remove single dimensions
tensor2 = tensor1.squeeze()

# Print out tensors and their shapes
print(tensor1, tensor1.shape)
print(tensor2, tensor2.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
